### PR TITLE
[WIP] Add full-width numbers support for `Time`, `Date`, `DateTime`, `DateRange`

### LINKED ISSUE #884: 🚀 - Add full-width numbers support for `Time`, `Date`, `DateTime`, `DateRange`
### Which package(s) are relevant/related to the feature request?

@maskito/kit

### Description

1. Move [`toHalfWidthNumber`](https://github.com/taiga-family/maskito/blob/main/projects/kit/src/lib/masks/number/utils/to-half-width-number.ts) to [`projects/kit/src/lib/utils`](https://github.com/taiga-family/maskito/tree/main/projects/kit/src/lib/utils).

2. Move [`createFullWidthToHalfWidthPreprocessor`](https://github.com/taiga-family/maskito/blob/main/projects/kit/src/lib/masks/number/processors/fullwidth-to-halfwidth-preprocessor.ts) to [`projects/kit/src/lib/processors`](https://github.com/taiga-family/maskito/tree/main/projects/kit/src/lib/processors).

3. And add `createFullWidthToHalfWidthPreprocessor` to  [`Time`](https://maskito.dev/kit/time), [`Date`](https://maskito.dev/kit/date), [`DateRange`](https://maskito.dev/kit/date-range), [`DateTime`](https://maskito.dev/kit/date-time).

4. Add Cypress Tests for full-width cases

Learn more:
* https://github.com/taiga-family/maskito/pull/864#discussion_r1447423820

### PR DESCRIPTION
**Pull request by rikusen0335**
## PR Type

What kind of change does this PR introduce?

- [ ] Bugfix
- [x] Feature
- [ ] Refactoring
- [ ] Build or CI related changes
- [ ] Tests related changes
- [ ] Documentation content changes

## What is the current behaviour?

Closes #884

This PR implements full-width to half-width preprocessor into time, or datetime or almost similar masks.

Please see issue page for more detail

## What is the new behaviour?

Above masks will have full-width to half-width preprocessor.

## Implementation
- Moved `createFullWidthToHalfWidthPreprocessor` from `projects/kit/src/lib/masks/number/processors` to `projects/kit/src/lib/processors` (also tests)
- Added `createFullWidthToHalfWidthPreprocessor` to `Time`, `Date`, `DateTime`, `DateRange` masks
- ~~Added e2e tests for `Time`, `Date`, `DateTime`, `DateRange` masks~~ _WIP_

### CODE REVIEW

**Comment by rikusen0335** [comment]
@nsbarsukov Idk who to mention, but I have a question. Have you tried IME/Do you have IME on your input method?

I am struggling with entering full-width numbers sometimes doesn't pass data, which is `{elementState, data}` used in processors.
I think [This part](https://github.com/taiga-family/maskito/blob/main/projects/core/src/lib/mask.ts#L115) does IME thing, but it doesn't work as I expected.

I can explain more in detail, but thinking about should I elaborate this to issue or slack something.

If you guys have time, please take a light look about this.

Thanks

**Comment by rikusen0335** [comment]
I'm working on date (or also date related) processors to fix this:
Still stuggling with how processors works...

https://github.com/taiga-family/maskito/assets/19174234/65293fb4-5483-40c3-b49e-d16bf8e542e4

**Comment by nsbarsukov** [comment]
@rikusen0335 Hello!

I've finally refactored code to improve support of IME composition for built-in `Date` / `DateRange` / `DateTime`.
*  https://github.com/taiga-family/maskito/pull/1027
* https://github.com/taiga-family/maskito/pull/1032

Now it will work in the following way:

https://github.com/taiga-family/maskito/assets/35179038/fc142d42-bc2d-4d43-a517-a39047163dc9

Could you rebase your branch, please ?
I think we can finish your PR and finally merge it.

**Comment by rikusen0335** [comment]
Will work on this for this weekend! Thank you for refactoring and sharing it! :))

**Comment by rikusen0335** [comment]
Due to complexity, I moved PR to #1043

**Pull request closed without merging**
